version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school_mgmt
    volumes:
      - ./seed_db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://school:school@postgres:5432/school_mgmt
      PORT: 5007
      JWT_SECRET: your_jwt_secret  # Set your secrets appropriately
    ports:
      - '5000:5007'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '5173:80'

volumes:
  postgres_data:
